default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] || "db" %>
  username: <%= ENV["DB_USERNAME"] || "admin" %>
  password: <%= ENV["DB_PASSWORD"] || "admin" %>
  port: <%= ENV["DB_PORT"] || 5432 %>

development:
  <<: *default
  database: hello_world

staging:
  <<: *default
  database: hello_world

production:
  <<: *default
  database: hello_world

test:
  <<: *default
  database: hello_world

